<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>33a101f4-1b77-44ae-a142-64f622358220</elementGuidId>
    <imagePath></imagePath>
    <name>link_yourTeam2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/div[1]/div[1]/section[1]/ul[2]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/myti/docs/manageteam') and equals(@text,'Your team')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Your team"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/myti/docs/manageteam</value>
        <webElementGuid>544345e9-b031-4402-9a62-48fbba5decce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Your team</value>
        <webElementGuid>544345e9-b031-4402-9a62-48fbba5decce</webElementGuid>
    </webElementProperties>
</WebElementEntity>