<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ac1a0aa2-e95a-4a57-b498-cc1ae0df1c5c</elementGuidId>
    <imagePath></imagePath>
    <name>main_orderConfirmation</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Home checkmarkYour order"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>