<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aee50638-2104-41e3-9640-7460e0f85579</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-store-checkout-dialog-launcher[1]/ti-dialog[1]/ti-button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-store-checkout-dialog-launcher &gt;&gt; internal:text="Save"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>