<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d96a100f-b604-4601-9fa9-edce543c8c1d</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-store-checkout-dialog-launcher[1]/ti-dialog[1]/div[1]/div[2]/ti-form-element[1]/ti-input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>