<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>36341e99-7a22-4172-89af-517aefa7034f</elementGuidId>
    <imagePath></imagePath>
    <name>link_viewCart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[11]/div[1]/div[1]/div[1]/div[1]/div[1]/ti-header-expandable-item-list[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/store/en-us/cart') and equals(@text,'View cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="View cart"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/store/en-us/cart</value>
        <webElementGuid>544345e9-b031-4402-9a62-48fbba5decce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View cart</value>
        <webElementGuid>544345e9-b031-4402-9a62-48fbba5decce</webElementGuid>
    </webElementProperties>
</WebElementEntity>