<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d28740a3-4055-4d92-b413-9db5457245d9</elementGuidId>
    <imagePath></imagePath>
    <name>ti_addedToCartDialog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-feature-dialog-launcher[1]/ti-dialog[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Added to cartTPS7A0512PDQNT200-mA, ultra-low-IQ, high-accuracy, low-dropout"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>