<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>49410046-1928-4eb8-842c-b862518b05a2</elementGuidId>
    <imagePath></imagePath>
    <name>ti_errorDialog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-feature-dialog-launcher[1]/ti-dialog[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Something went wrongWe cannot"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>