<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eb3db642-32cd-4607-be12-c4217c939a8e</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-list-manager-dialog-launcher[1]/ti-dialog[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Create ListThat name is"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>