<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5a72e5c7-e2fe-43c8-92e2-1f49bc2cff82</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[2]/div[2]/div[1]/ti-login[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-login</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>