<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>87f8f569-485a-427f-9721-9fde8dcdbef8</elementGuidId>
    <imagePath></imagePath>
    <name>atomic_CategoryFacet</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/atomic-search-interface[1]/atomic-search-layout[1]/atomic-layout-section[1]/div[1]/atomic-category-facet[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>atomic-category-facet &gt;&gt; internal:has-text="ApplicationsValues for the"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>