<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b34dff17-1d56-437d-bbf7-be8c8c843b66</elementGuidId>
    <imagePath></imagePath>
    <name>main_internalDocumentation</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="${main_internalDocumentation_internalText}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>