<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6a9e3161-f6a2-4e3f-8f35-40830242b5e5</elementGuidId>
    <imagePath></imagePath>
    <name>ti_Login</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[2]/div[2]/div[1]/ti-login[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-login</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>