<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ae1164e-69fc-41f1-8b8c-f914cd534c01</elementGuidId>
    <imagePath></imagePath>
    <name>ti_dynamicObject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-store-checkout-wrapper[1]/div[3]/div[1]/div[1]/ti-store-checkout-stepper-wrapper[1]/ti-store-checkout-stepper[1]/ti-store-checkout-step[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="${ti_dynamicObject_internalText}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>