<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4180fc0e-7125-408a-997e-0fbb61a82e66</elementGuidId>
    <imagePath></imagePath>
    <name>div_CategoriesListing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ti_aem-application-CategoriesListing &gt; div:nth-child(2)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>