<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>624f1f3c-d3c8-44d2-bbe9-bf0a38b802d9</elementGuidId>
    <imagePath></imagePath>
    <name>link_ReferenceDesigns</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'//www-uat.itg.ti.com{{url}}') and equals(@text,'Reference designs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Reference designs"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>//www-uat.itg.ti.com{{url}}</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Reference designs</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
</WebElementEntity>