<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>32489970-26d6-4eb2-b6dc-7048db076b5e</elementGuidId>
    <imagePath></imagePath>
    <name>link_ProfessionalAudioAmplifier</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/div[1]/div[1]/div[1]/div[12]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[10]/ul[13]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://www.ti.com/solution/professional-audio-amplifier-rack-mount') and equals(@text,'Professional audio amplifier (rack mount)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Professional audio amplifier"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.ti.com/solution/professional-audio-amplifier-rack-mount</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Professional audio amplifier (rack mount)</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
</WebElementEntity>