<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5102588d-3693-41af-826b-a4a3bb10aa84</elementGuidId>
    <imagePath></imagePath>
    <name>div_shippingBillingAddress</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-store-checkout-wrapper[1]/div[3]/div[1]/div[1]/ti-store-checkout-stepper-wrapper[1]/ti-store-checkout-stepper[1]/ti-store-checkout-step[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Shipping and billing address"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>