<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f3f1d7b-79b1-4588-81c2-250b0dcf3b5f</elementGuidId>
    <imagePath></imagePath>
    <name>ti_checkoutDialogCancel</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-store-checkout-dialog-launcher[1]/ti-dialog[1]/ti-button[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-store-checkout-dialog-launcher &gt;&gt; internal:text="Cancel"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>