<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>938810a2-8eb5-4bac-8164-ec854b4b02a0</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-store-checkout-wrapper[1]/div[3]/div[1]/div[1]/ti-store-checkout-stepper-wrapper[1]/ti-store-checkout-stepper[1]/ti-store-checkout-step[1]/div[2]/ti-store-checkout-shipping-methods[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["ti-store-checkout-shipping-methods"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>