<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dff38983-137a-4321-bf1a-5641728dd7b3</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-store-checkout-wrapper[1]/div[3]/div[1]/div[1]/ti-store-checkout-stepper-wrapper[1]/ti-store-checkout-stepper[1]/ti-store-checkout-step[1]/div[2]/ti-store-checkout-address[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-store-checkout-address</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>