<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>10218cd4-b6ef-4ec1-a963-e8e5ef0ef4f1</elementGuidId>
    <imagePath></imagePath>
    <name>ti_Breadcrumb</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ti-breadcrumb[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Home Applications Industrial Automotive Communications equipment Enterprise"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>