<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f76a515d-97f7-40f2-b81a-1b98301b9414</elementGuidId>
    <imagePath></imagePath>
    <name>ti_checkoutProfileInformation</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/ti-checkout-profile-add-edit-cop[1]/div[3]/div[1]/ti-checkout-profile-stepper-wrapper[1]/ti-checkout-profile-stepper[1]/ti-checkout-profile-step[1]/div[2]/ti-checkout-profile-information[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-checkout-profile-information</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>