<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>50c3a761-60af-4371-b918-64659da2c3a1</elementGuidId>
    <imagePath></imagePath>
    <name>ti_checkoutProfileTax</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/ti-checkout-profile-add-edit-cop[1]/div[3]/div[1]/ti-checkout-profile-stepper-wrapper[1]/ti-checkout-profile-stepper[1]/ti-checkout-profile-step[3]/div[2]/ti-checkout-profile-tax[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-checkout-profile-tax</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>