<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>23c6da56-0829-4e5a-93a2-d69f10e84032</elementGuidId>
    <imagePath></imagePath>
    <name>div_StoryWithTabs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[3]/div[1]/div[1]/div[1]/div[4]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/ti-tab-container[1]/ti-tab-panel[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(3) &gt; .xf-content-height &gt; .aem-Grid &gt; .storyWithTabs &gt; .ti_aem-storywithtabs &gt; ti-tab-container &gt; ti-tab-panel &gt; .ti_aem-storywithtabs-section &gt; div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>