<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6aea527f-cfb7-4f2d-84f9-fd884bff9471</elementGuidId>
    <imagePath></imagePath>
    <name>ti_avlOrderableFilterableTable</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-avl-singlepart-results[1]/div[1]/ti-avl-search-result-container[1]/ti-avl-table-controller[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/ti-avl-expansion-view[1]/div[1]/div[1]/ti-avl-orderable-filterable-table[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-avl-orderable-filterable-table</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>