<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>961242aa-47ac-4eb1-a5fb-2bb50bc8b5b4</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-avl-singlepart-results[1]/div[1]/ti-avl-search-result-container[1]/ti-avl-table-controller[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=cell[name="chevron-down View alternates"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>