<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ea792090-4e29-4623-a17d-e77877243fe9</elementGuidId>
    <imagePath></imagePath>
    <name>ti_TabContainer5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[3]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/ti-tab-container[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-tab-container &gt;&gt; internal:has-text="Time Location/Session Session"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>