<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd332f1b-1c89-42b6-a38f-cab7f481b89e</elementGuidId>
    <imagePath></imagePath>
    <name>link_MaddysList</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-list-manager-wrapper[1]/section[3]/div[1]/ti-list-manager-grid[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://www-uat.itg.ti.com/list-manager/en-US/11') and equals(@text,'maddys list')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="maddys list"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www-uat.itg.ti.com/list-manager/en-US/11</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>maddys list</value>
        <webElementGuid>f3821852-7244-4265-9ab2-c0f1e89a3715</webElementGuid>
    </webElementProperties>
</WebElementEntity>