<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f66463a-6893-4cf1-bb16-d3a21b73c75d</elementGuidId>
    <imagePath></imagePath>
    <name>div_customReelsWarning</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/ti-store-cart-wrapper[1]/div[6]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text="Custom reels cannot be"i &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>