<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2f3b81c1-4600-4359-bf97-6954ce6ae71d</elementGuidId>
    <imagePath></imagePath>
    <name>p_paragraph</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/footer[1]/div[1]/div[2]/div[2]/p[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=paragraph &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>