<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5aededc9-22b6-4562-825f-1d4068de1b15</elementGuidId>
    <imagePath></imagePath>
    <name>ti_checkoutDialogLauncher</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-store-checkout-dialog-launcher[1]/ti-dialog[1]/ti-button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-store-checkout-dialog-launcher &gt;&gt; internal:text="OK"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>